/**
 * generated by Xtext
 */
package org.xtext.lua.validation;

import org.xtext.lua.validation.AbstractLuaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LuaValidator extends AbstractLuaValidator {
}
