/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.tests;

import com.google.inject.Inject;
import com.google.inject.Provider;
import exec_iot_lua.revisitor.impl.Exec_iot_luaRevisitor;
import exec_iot_lua.revisitor.operations.exec_iot_lua.IotActivityOperation;
import iot.lua.xtext.tests.IotLuaXtextInjectorProvider;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(IotLuaXtextInjectorProvider.class)
@SuppressWarnings("all")
public class IotLuaXtextExecutionTest {
  @Inject
  private Provider<ResourceSet> rsp;
  
  @Test
  public void loadModel() {
    try {
      final ResourceSet rs = this.rsp.get();
      final Resource r = rs.getResource(URI.createURI("usecase.iot_lua"), true);
      r.load(null);
      EObject _head = IterableExtensions.<EObject>head(r.getContents());
      final iot.System s = ((iot.System) _head);
      final Exec_iot_luaRevisitor rev = new Exec_iot_luaRevisitor() {
      };
      final IotActivityOperation o = rev.$(s.getSketch().getActivity());
      o.main();
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
