/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.validation;

import iot.lua.xtext.validation.AbstractIotLuaXtextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotLuaXtextValidator extends AbstractIotLuaXtextValidator {
}
