/**
 * generated by Xtext 2.12.0
 */
package ale.xtext.ide;

import ale.xtext.ide.AbstractAleIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AleIdeModule extends AbstractAleIdeModule {
}
