/**
 * generated by Xtext 2.12.0
 */
package ale.xtext.ide;

import ale.xtext.AleRuntimeModule;
import ale.xtext.AleStandaloneSetup;
import ale.xtext.ide.AleIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AleIdeSetup extends AleStandaloneSetup {
  @Override
  public Injector createInjector() {
    AleRuntimeModule _aleRuntimeModule = new AleRuntimeModule();
    AleIdeModule _aleIdeModule = new AleIdeModule();
    return Guice.createInjector(Modules2.mixin(_aleRuntimeModule, _aleIdeModule));
  }
}
