/**
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext.ui;

import iot.simpleexpressions.xtext.ui.AbstractIoTUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IoTUiModule extends AbstractIoTUiModule {
  public IoTUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
