/*
 * generated by Xtext 2.14.0
 */
package iot.lua.xtext.ui.tests;

import com.google.inject.Injector;
import iot.lua.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IotLuaXtextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("iot.lua.xtext.IotLuaXtext");
	}

}
