/**
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext.validation;

import iot.simpleexpressions.xtext.validation.AbstractIoTValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IoTValidator extends AbstractIoTValidator {
}
