/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ui;

import ale.xtext.ui.AbstractAleUiModule;
import ale.xtext.ui.hyperlink.AleHyperlinkHelper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AleUiModule extends AbstractAleUiModule {
  @Override
  public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
    return AleHyperlinkHelper.class;
  }
  
  public AleUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
