/**
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext;

import iot.simpleexpressions.xtext.AbstractIoTRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IoTRuntimeModule extends AbstractIoTRuntimeModule {
}
