/**
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext;

import iot.simpleexpressions.xtext.IoTStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IoTStandaloneSetup extends IoTStandaloneSetupGenerated {
  public static void doSetup() {
    new IoTStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
