/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import iot.lua.xtext.IotLuaXtextRuntimeModule;
import iot.lua.xtext.IotLuaXtextStandaloneSetup;
import iot.lua.xtext.ide.IotLuaXtextIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IotLuaXtextIdeSetup extends IotLuaXtextStandaloneSetup {
  @Override
  public Injector createInjector() {
    IotLuaXtextRuntimeModule _iotLuaXtextRuntimeModule = new IotLuaXtextRuntimeModule();
    IotLuaXtextIdeModule _iotLuaXtextIdeModule = new IotLuaXtextIdeModule();
    return Guice.createInjector(Modules2.mixin(_iotLuaXtextRuntimeModule, _iotLuaXtextIdeModule));
  }
}
