/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.ide;

import iot.lua.xtext.ide.AbstractIotLuaXtextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IotLuaXtextIdeModule extends AbstractIotLuaXtextIdeModule {
}
