/**
 * generated by Xtext 2.10.0
 */
package ale.xtext;

import ale.xtext.AbstractAleRuntimeModule;
import ale.xtext.compiler.AleJvmModelGenerator;
import ale.xtext.typesystem.computation.AleTypeComputer;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AleRuntimeModule extends AbstractAleRuntimeModule {
  public Class<? extends ITypeComputer> bindITypeComputer() {
    return AleTypeComputer.class;
  }
  
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return AleJvmModelGenerator.class;
  }
}
