/**
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext.ide;

import iot.simpleexpressions.xtext.ide.AbstractIoTIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IoTIdeModule extends AbstractIoTIdeModule {
}
