/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext;

import iot.lua.xtext.IotLuaXtextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotLuaXtextStandaloneSetup extends IotLuaXtextStandaloneSetupGenerated {
  public static void doSetup() {
    new IotLuaXtextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
