/**
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext;

import iot.lua.xtext.AbstractIotLuaXtextRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotLuaXtextRuntimeModule extends AbstractIotLuaXtextRuntimeModule {
}
