/*
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.tests

import com.google.inject.Inject
import com.google.inject.Provider
import exec_iot_lua.revisitor.impl.Exec_iot_luaRevisitor
import iot.System
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(IotLuaXtextInjectorProvider)
class IotLuaXtextExecutionTest {

	@Inject
	Provider<ResourceSet> rsp

	@Test
	def void loadModel() {

		val rs = rsp.get
		val r = rs.getResource(URI.createURI("usecase.iot"), true)
		r.load(null)

		val s = r.contents.head as System

		val rev = new Exec_iot_luaRevisitor() {
		}
		val o = rev.$(s.sketch.activity)
		o.main()
	}
}
